name: Build & Push Multi-Arch Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'  # reaguje na dowolny tag, np. v1.0.5

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: DockerHub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: GitHub Container Registry login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/agatogr/zadanie2
        tags: |
          type=ref,event=tag
          type=sha

    - name: Debug metadata (opcjonalne)
      run: |
        echo "Tags: ${{ steps.meta.outputs.tags }}"
        echo "Version: ${{ steps.meta.outputs.version }}"

    - name: Build & push image (multi-arch)
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/agatogr/zadanie2:${{ github.ref_name }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=docker.io/agatog/ci-cache:latest
        cache-to: type=registry,ref=docker.io/agatog/ci-cache:latest,mode=max

    - name: Scan image for CVEs using Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/agatogr/zadanie2:${{ github.ref_name }}
        format: table
        severity: CRITICAL,HIGH
        exit-code: 1
